version: 1.0.{build}
before_build:
- ps: test
build:
  verbosity: minimal
after_build:
- cmd: packages\Tools.InnoSetup.5.5.6\tools\ISCC Install\Gwent.iss
artifacts:
- path: Gwent\Install\Installer
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: Release from appveyor
  auth_token:
    secure: /d5+C/5V/gtAbaF+Vl7C3w93C97/faXx2JjoTN5CpvyvdA0ITYGarW38UzBDrEOe
  artifact: Gwent\Install\Installer.zip
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true